// Contract metadata
export const contract = {
  name: "Independent Contractor Services Agreement",
  parties: "Nexus Digital Solutions LLC \u2194 Contractor",
  effectiveDate: "March 1, 2026",
  term: "12 months (auto-renews)",
  value: "$15,000",
  governingLaw: "British Virgin Islands",
  type: "Freelancer / Independent Contractor",
  score: 18,
  grade: "F",
  label: "DANGEROUS",
};

// Agent definitions
export const agents = [
  {
    id: "clause",
    name: "Clause Analyst",
    color: "#22c55e",
    colorDim: "rgba(34,197,94,0.12)",
    weight: "20%",
    duration: 3200,
    summary: "30 clauses \u00b7 11 sections",
    events: [
      { time: 400, type: "info", badge: "Scan", summary: "Reading contract... 4 pages, 11 sections identified" },
      { time: 900, type: "info", badge: "Section", summary: "Section 1: Scope of Services \u2014 4 clauses extracted" },
      { time: 1300, type: "info", badge: "Section", summary: "Section 2: Compensation \u2014 4 clauses extracted" },
      { time: 1600, type: "medium", badge: "Section", summary: "Section 3: Intellectual Property \u2014 3 clauses, pre-existing IP assignment flagged",
        detail: { title: "Section 3.2 \u2014 Pre-Existing IP Assignment", risk: "HIGH", text: "Assignment includes pre-existing IP, tools, frameworks, libraries, code snippets, templates, and methodologies. This transfers ownership of Contractor's entire toolkit.", fix: "Limit assignment to custom work product only. License pre-existing tools to Client." }},
      { time: 1900, type: "info", badge: "Section", summary: "Section 4: Confidentiality \u2014 3 clauses, perpetual NDA noted" },
      { time: 2100, type: "high", badge: "Section", summary: "Section 5: Non-Compete \u2014 24-month restriction across all technology",
        detail: { title: "Section 5.1 \u2014 Non-Competition", risk: "HIGH", text: "24-month non-compete covering the entire 'technology industry' for an independent contractor. Effectively bans Contractor from working for 2 years.", fix: "Delete non-compete entirely or narrow to 6-month non-solicitation of named competitors." }},
      { time: 2500, type: "high", badge: "Section", summary: "Section 6: Termination \u2014 5 clauses, severe asymmetry detected" },
      { time: 2700, type: "high", badge: "Section", summary: "Section 7-8: Indemnification & Liability \u2014 unlimited Contractor liability" },
      { time: 2900, type: "medium", badge: "Section", summary: "Sections 9-11: Warranties, Governing Law, General Provisions" },
      { time: 3100, type: "info", badge: "Complete", summary: "Clause analysis complete: 30 clauses \u2014 23 favor Client, 0 favor Contractor, 7 neutral" },
    ],
  },
  {
    id: "risk",
    name: "Risk Assessor",
    color: "#ef4444",
    colorDim: "rgba(239,68,68,0.12)",
    weight: "25%",
    duration: 4500,
    summary: "20 high \u00b7 8 med \u00b7 2 low",
    events: [
      { time: 500, type: "info", badge: "Init", summary: "Scoring each clause from Contractor's perspective..." },
      { time: 1000, type: "high", badge: "10/10", summary: "Section 1.3: Unlimited revisions \u2014 $50K-$150K+ uncompensated labor exposure",
        detail: { title: "Unlimited Revisions \u2014 Section 1.3", risk: "HIGH (10/10)", text: "No cap on revision cycles with subjective 'full satisfaction' standard. Client can demand endless rewrites at no additional cost. Combined with fixed $15K fee, this creates an infinite work obligation.", fix: "Cap at 2 revision rounds per milestone. Additional rounds at $150/hr. Add deemed-acceptance after 5 business days." }},
      { time: 1500, type: "high", badge: "10/10", summary: "Section 3.2: Pre-existing IP seizure \u2014 $50K-$500K+ in tools and frameworks at risk",
        detail: { title: "Pre-Existing IP Assignment \u2014 Section 3.2", risk: "HIGH (10/10)", text: "Transfers ownership of Contractor's pre-existing tools, frameworks, libraries, templates. Could strip Contractor of ability to use their own tools on future projects. Potentially destroys their entire business.", fix: "Assign only custom work product. Contractor retains pre-existing IP with non-exclusive license to Client." }},
      { time: 2000, type: "high", badge: "10/10", summary: "Section 5.1: 24-month non-compete \u2014 $160K-$240K lost income exposure",
        detail: { title: "24-Month Non-Compete \u2014 Section 5.1", risk: "HIGH (10/10)", text: "Bars Contractor from entire 'technology industry' for 2 years. Almost certainly unenforceable (void in CA, CO, MN, OK, ND) but creates massive litigation risk. FTC has also moved to restrict non-competes.", fix: "Delete entirely. If Client insists, limit to 6-month non-solicitation of 3 named direct competitors with paid restriction fee." }},
      { time: 2500, type: "high", badge: "10/10", summary: "Section 7.1: Indemnification for Client's own negligence \u2014 unlimited exposure",
        detail: { title: "Indemnification \u2014 Section 7.1", risk: "HIGH (10/10)", text: "Contractor indemnifies Client for ALL claims including those caused by Client's own negligence. One-way, no cap, survives indefinitely. Contractor is effectively Client's insurer.", fix: "Make indemnification mutual. Exclude claims from other party's negligence. Cap at contract value." }},
      { time: 3000, type: "high", badge: "10/10", summary: "Section 8.3: Unlimited Contractor liability on $15K contract \u2014 entire net worth at risk" },
      { time: 3400, type: "high", badge: "9/10", summary: "Section 2.2: 90-day payment terms + subjective withholding right" },
      { time: 3700, type: "high", badge: "9/10", summary: "Section 6.3+6.5: Client can terminate immediately, owes nothing for completed work" },
      { time: 4000, type: "high", badge: "8/10", summary: "Sections 10.1-10.2: BVI governing law and courts \u2014 dispute suppression mechanism" },
      { time: 4200, type: "medium", badge: "6/10", summary: "Section 6.2: Auto-renewal trap \u2014 120-day cancellation window" },
      { time: 4400, type: "info", badge: "Complete", summary: "Risk assessment complete: Overall 9.2/10 CRITICAL \u2014 exposure $420K-$1.2M+ vs $15K contract" },
    ],
  },
  {
    id: "compliance",
    name: "Compliance Checker",
    color: "#a855f7",
    colorDim: "rgba(168,85,247,0.12)",
    weight: "20%",
    duration: 3800,
    summary: "4 critical \u00b7 6 high",
    events: [
      { time: 400, type: "info", badge: "Init", summary: "Checking federal, state, and regulatory compliance..." },
      { time: 800, type: "critical", badge: "CRITICAL", summary: "Worker misclassification risk \u2014 business hours requirement + unilateral control = employment indicators",
        detail: { title: "Worker Misclassification", risk: "CRITICAL", text: "Business-hours availability (1.4), unilateral scope control (1.2), 12-month term (6.1) resemble employment, not independent contracting. Fails ABC test used in CA/20+ states. IRS reclassification triggers back taxes, FICA, FUTA, penalties.", fix: "Remove mandatory availability hours. Add formal change order process. Give Contractor control over methods and schedule." }},
      { time: 1200, type: "critical", badge: "CRITICAL", summary: "Non-compete unenforceable \u2014 void in CA, CO, MN, OK, ND; FTC rule prohibits broadly",
        detail: { title: "Non-Compete Enforceability", risk: "CRITICAL", text: "24-month technology-industry ban violates: California Bus. & Prof. Code \u00a716600, Colorado (for workers below threshold), Minnesota, Oklahoma, North Dakota outright bans. FTC final rule (2024) broadly prohibits non-competes. Even in permissive states, scope is facially overbroad.", fix: "Remove non-compete entirely. Replace with narrow 6-12 month non-solicitation of direct clients only." }},
      { time: 1600, type: "critical", badge: "CRITICAL", summary: "Pre-existing IP assignment \u2014 unconscionable; conflicts with open-source licenses" },
      { time: 2000, type: "critical", badge: "CRITICAL", summary: "BVI choice of law \u2014 no nexus to parties; likely struck down; suggests regulatory evasion",
        detail: { title: "BVI Governing Law", risk: "CRITICAL", text: "Neither party nor work has connection to British Virgin Islands. Under Restatement (Second) of Conflict of Laws \u00a7187, courts may override when chosen state has no substantial relationship. Appears designed to evade U.S. contractor protections. Delaware LLC should use Delaware law.", fix: "Change to Delaware law or Contractor's home state. Use AAA arbitration in a mutually convenient U.S. location." }},
      { time: 2400, type: "high", badge: "HIGH", summary: "Indemnification for own negligence \u2014 void under anti-indemnity statutes in multiple states" },
      { time: 2700, type: "high", badge: "HIGH", summary: "Missing DTSA whistleblower notice \u2014 required by 18 U.S.C. \u00a71833(b)" },
      { time: 3000, type: "medium", badge: "MODERATE", summary: "No Data Processing Agreement \u2014 website migration may involve PII; CCPA/GDPR gaps" },
      { time: 3300, type: "high", badge: "HIGH", summary: "Aggregate unconscionability \u2014 cumulative one-sidedness supports judicial intervention (UCC \u00a72-302)" },
      { time: 3700, type: "info", badge: "Complete", summary: "Compliance check complete: 4 CRITICAL, 6 HIGH severity issues \u2014 contract likely unenforceable in multiple areas" },
    ],
  },
  {
    id: "terms",
    name: "Terms Mapper",
    color: "#06b6d4",
    colorDim: "rgba(6,182,212,0.12)",
    weight: "15%",
    duration: 5200,
    summary: "19 obligations \u00b7 7 deadlines",
    events: [
      { time: 500, type: "info", badge: "Init", summary: "Mapping all duties, deadlines, triggers, and consequences..." },
      { time: 1000, type: "info", badge: "Obligat.", summary: "Contractor: 19 obligations identified (performance, IP, confidentiality, non-compete, indemnification)" },
      { time: 1500, type: "info", badge: "Obligat.", summary: "Client: 1 obligation identified (pay $15,000 across 4 milestones within 90 days of invoice)" },
      { time: 2000, type: "high", badge: "Asymmetry", summary: "Obligation ratio: 19 Contractor vs 1 Client \u2014 severely one-sided",
        detail: { title: "Obligation Asymmetry", risk: "HIGH", text: "Contractor has 19 distinct obligations including unlimited revisions, business hours availability, perpetual confidentiality, 24-month non-compete, unlimited indemnification, and unlimited liability. Client's only obligation is payment (with 90-day terms and subjective withholding rights).", fix: "Add Client cooperation obligations: timely feedback (10 business days), provide materials/access, act in good faith on spec changes." }},
      { time: 2500, type: "medium", badge: "Deadline", summary: "Critical date: Oct 31, 2026 \u2014 last day to prevent auto-renewal (120-day notice required)" },
      { time: 3000, type: "high", badge: "Trigger", summary: "Termination: Client immediate/no-cause/no-pay vs Contractor 90-day notice + must keep working",
        detail: { title: "Termination Trigger Map", risk: "HIGH", text: "Client: terminate immediately, no cause needed, no payment for WIP. Contractor: must give 90 days written notice, must continue all obligations during notice period, forfeits unpaid work. Auto-renewal locks Contractor in for another 12 months if 120-day window missed.", fix: "Mutual 15-day notice. Payment for all work through termination date. Remove auto-renewal for project-based work." }},
      { time: 3500, type: "high", badge: "Survival", summary: "Post-termination: Sections 3,4,5,7,8,10 survive \u2014 all one-sided Contractor obligations" },
      { time: 4000, type: "info", badge: "Missing", summary: "12 missing protections identified: change orders, acceptance criteria, Client cooperation, mutual indemnity, DPA..." },
      { time: 4500, type: "high", badge: "Exposure", summary: "Financial exposure: $420K-$1.2M+ against $15K contract value \u2014 risk ratio 28:1 to 82:1" },
      { time: 5100, type: "info", badge: "Complete", summary: "Terms mapping complete: 19 Contractor obligations, 1 Client obligation, 7 critical deadlines, 12 missing protections" },
    ],
  },
  {
    id: "recommendation",
    name: "Recommendations",
    color: "#f97316",
    colorDim: "rgba(249,115,22,0.12)",
    weight: "20%",
    duration: 6000,
    summary: "7 critical \u00b7 4 high \u00b7 3 med",
    events: [
      { time: 600, type: "info", badge: "Init", summary: "Generating specific counter-proposals with replacement language..." },
      { time: 1200, type: "critical", badge: "FIX #1", summary: "Pre-existing IP: Assign only custom work; license pre-existing tools; condition on full payment",
        detail: { title: "Fix: Pre-Existing IP (Section 3.2)", risk: "CRITICAL \u2014 Walk Away If Refused", text: "Current: All pre-existing IP, tools, frameworks assigned to Client.\n\nProposed: Contractor retains pre-existing IP. Grants Client a non-exclusive, perpetual, royalty-free license to use Contractor Tools solely as embedded in delivered Work Product. IP assignment conditioned on full payment.", fix: "Contractor retains all right, title, and interest in any tools, frameworks, libraries, templates, or methodologies that existed prior to this Agreement. Client receives a non-exclusive, perpetual, royalty-free license to use such materials solely as embedded in the delivered Work Product." }},
      { time: 1800, type: "critical", badge: "FIX #2", summary: "Unlimited revisions: Cap at 2 rounds per milestone, $150/hr beyond, 5-day acceptance window",
        detail: { title: "Fix: Unlimited Revisions (Section 1.3)", risk: "CRITICAL \u2014 Walk Away If Refused", text: "Current: Unlimited revisions at no cost until Client declares 'full satisfaction'.\n\nProposed: 2 revision rounds per milestone included. Additional rounds billed at $150/hr. Client has 5 business days to provide feedback; silence = acceptance.", fix: "Each milestone includes two (2) rounds of revisions. A 'revision round' consists of one consolidated set of written feedback submitted within five (5) business days. Additional rounds billed at $150/hr with written estimate approval required." }},
      { time: 2400, type: "critical", badge: "FIX #3", summary: "Payment: Net 30 (not 90), 25% deposit, objective acceptance, 1.5%/mo late fee",
        detail: { title: "Fix: Payment Terms (Section 2.2)", risk: "CRITICAL", text: "Current: 90-day payment terms, subjective 'unsatisfactory' withholding.\n\nProposed: Non-refundable 25% deposit ($3,750) upfront. Remaining milestones Net 30. 10-business-day acceptance with specific written objections required. 1.5%/mo late fee. Right to suspend after 45 days unpaid.", fix: "Payment within thirty (30) days of invoice. Client has ten (10) business days to accept or provide specific written objections. Non-response = deemed acceptance. Late invoices accrue 1.5% monthly interest." }},
      { time: 3000, type: "critical", badge: "FIX #4", summary: "Non-compete: Delete entirely; replace with narrow 6-month non-solicitation if needed" },
      { time: 3600, type: "critical", badge: "FIX #5", summary: "Termination: Mutual 15-day notice; pro-rata payment for WIP; IP conditioned on full payment" },
      { time: 4000, type: "critical", badge: "FIX #6", summary: "Liability: Mutual cap at $15K contract value; mutual indemnification; exclude own negligence" },
      { time: 4400, type: "critical", badge: "FIX #7", summary: "Governing law: Delaware or Contractor's state; AAA arbitration; small-claims exception" },
      { time: 4800, type: "high", badge: "FIX #8", summary: "Portfolio: Permit use of final deliverables; allow Client reference; optional 90-day delay" },
      { time: 5200, type: "high", badge: "FIX #9", summary: "Termination symmetry: Mutual 15-day notice; add for-cause termination for both parties" },
      { time: 5500, type: "medium", badge: "FIX #10", summary: "Auto-renewal: Remove for project work; or convert to month-to-month with 30-day notice" },
      { time: 5800, type: "info", badge: "Complete", summary: "14 fixes generated: 7 CRITICAL (walk-away issues), 4 HIGH, 3 MEDIUM \u2014 DO NOT SIGN without addressing all critical items" },
    ],
  },
];
